### ISSUE TITLE
Is comparing signatures better than using SHA1?

### ISSUE THREAD

**Issue by jtlapp** [tj/node-cookie-signature#20]
The signature is cryptographically random, so why not just compare the received signature to the expected signature? That way timing attacks are only being done against randomized values, and there is no need to perform two computationally expensive SHA1 hashes for each cookie.

[According to Wikipedia](https://en.wikipedia.org/wiki/Birthday_attack), a birthday attack on SHA-256 would require 4.8 * 10^35 different in-use signatures in order for the attacker to have a one-millionth percent chance of selecting an in-use signature. Those are pretty slim odds for even a highly improbable scenario.

Moreover, the currently in-use SHA1 hash maps the 256 cryptographically random bits of the SHA-256 signature (plus the data bits) into only 160 random bits, increasing the odds of collision available to an attacker.

It seems that comparing signatures directly may be sufficient to make timing attacks infeasible, while also greatly improving performance and reducing attack vulnerability. What am I missing?

(See also issue #15 discussion on dealing with timing attacks via SHA1.)

**Comment by jtlapp** [comment]
Oops. Give me a moment to revise this. The data tested is the data submitted!

**Comment by jtlapp** [comment]
Okay, closing this. The attacker can figure out the expected signature through a timing attack. Revisiting...

**Comment by natevw** [comment]
Yep, glad you could figure it out. It's a bit surprising at first look at the code, but the rationale is in the other ticket you found. Potentially worth explaining better in the code itself at some point, but hopefully amply documented here in the meantime.

**Comment by jtlapp** [comment]
Thanks for your response. I originally posted regarding session IDs that the server would confirm, but your module confirms signatures without confirming the data, making my original observation irrelevant.

Any thoughts on the business of constant-time checking 256 cryptographically random bits of signature vs generating two SHA1 hashes at more CPU expense with less cryptographic strength (160 bits)? (As posted to the other thread.)
