### ISSUE TITLE
Who is the copyright holder?

### ISSUE THREAD

**Issue by bduranc** [tj/node-cookie-signature#28]
Greetings,

I see this repository is owned by TJ Holowaychuk but the copyright holder appears to be "LearnBoost" when one takes a look at the license info posted on the main page.

Is TJ Holowaychuck the copyright holder? or is LearnBoost, Inc.?

Thanks.
Brian

**Comment by natevw** [comment]
Apparently TJ considered LearnBoost, Inc. the copyright holder when he wrote it. There have since been other contributions, and so the short answer to "who is the copyright holder" isn't particularly short: https://github.com/tj/node-cookie-signature/graphs/contributors

**Comment by bduranc** [comment]
thank you for the response.
