### ISSUE TITLE
Adding License text on a separate file.

### ISSUE THREAD

**Issue by ranadewa** [tj/node-cookie-signature#30]
Please add a separate License file as it makes the oss automation easy.

**Comment by natevw** [comment]
@ranadewa Pull request would be appreciated! The license is currently specified in both the `package.json` and readme, but it sounds like a copy within a separate License.md file is something that could be handy?

**Comment by ranadewa** [comment]
@natevw [pull request]( https://github.com/tj/node-cookie-signature/pull/31 ) created.
