### ISSUE TITLE
Browser implementation

### ISSUE THREAD

**Issue by franciscop** [tj/node-cookie-signature#32]
Hi, I'm trying to load something like this in a [Cloudflare Worker](https://workers.cloudflare.com/) environment. I got something working that selectively loads either the Node.js or the [Browser crypto implementation](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto) (which is available in a worker), would you be interested in this functionality within this package? With esm it's like:

```js
const nodeHash = async message => {
  const crypto = await import("crypto");
  return crypto
    .createHash("sha256")
    .update(message)
    .digest("hex");
};

const browserHash = async message => {
  const msgUint8 = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest("SHA-256", msgUint8);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
};

export const hash = typeof crypto === "undefined" ? nodeHash : browserHash;
```

I would convert it to ES5/commonjs for a PR and convert it to e.g. the base64 and hmac() methods used in `node-cookie-signature`.

**Comment by franciscop** [comment]
Fixed, published a similar package that also works on the browser with the [Browser crypto](https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto):

https://www.npmjs.com/package/sign

**Comment by natevw** [comment]
Thanks @franciscop and apologies for not replying earlier. Unless I hear otherwise from the ExpressJS team, I think it's best to keep this library minimal and stable.

Your version looks like a nice modern API and I'm sure will be useful to others! 👍

**Comment by franciscop** [comment]
Sure, no problem at all and thanks for the reply! For now I need it myself, I am trying to sign cookies on an environment that has access to the browser API but not to Node.js API.

`sign` is still in alpha, I'm strongly considering just using node-cookie-signature implementation (for the Node.js part) for both compatibility, testing and to avoid reinventing the wheel. So converting it to base64+removing some chars.

Anyway, thanks for creating and maintaining this package!
