### ISSUE TITLE
Export sign function

### ISSUE THREAD

**Issue by daveisfera** [tj/node-cookie-signature#35]
This is a request that the sign function be exported so it can be used by services that want to generate a cookie (like creating and driving a headless browser session for screenshot/PDF generation). Currently, we're doing this by having our own function that matches the behavior, but this is fragile and it would be nice to be able to use the actual function.

Follow on from this issue: https://github.com/expressjs/session/issues/805

**Comment by natevw** [comment]
Hi Dave, both the `sign` and `unsign` functions are exported by this library, e.g.

```
import {sign} from 'cookie-signature';

let result = sign("thing", SOME_SECRET);
// …use `result`
```

should already work. Feel free to re-open if I've misunderstood your request.

**Comment by daveisfera** [comment]
🤦 sorry for the noise
