### ISSUE TITLE
[Bug] Unsigning fails when cookie value was stringified with JSON.stringify 

### ISSUE THREAD

**Issue by oelbaganwg** [tj/node-cookie-signature#37]
When you stringify a string unsigning doesnt work:

works
`const val = 'whatever'`
`const signedCookie = cookie.sign(val, 'secret')`
`cookie.unsign(signedCookie, 'secret')`

doesn't work
`const val = JSON.stringify('whatever')`
`const signedCookie = cookie.sign(val, 'secret')`
`cookie.unsign(signedCookie, 'secret')`

This doesn't make sense because many cookie values need to be stringified especially when they have object values. Is there anway for this to work with stringified text?

**Comment by natevw** [comment]
This works as expected for me:

```
const cookie = require('cookie-signature');
const key = 'secret';

function test1() {
  const val = 'whatever';
  const signedCookie = cookie.sign(val, key);
  return cookie.unsign(signedCookie, key);
}


function test2() {
  const val = JSON.stringify('whatever');
  const signedCookie = cookie.sign(val, key);
  return cookie.unsign(signedCookie, key);
}

console.log(test1());
console.log(test2());
```

Logs:

> whatever
> "whatever"

Perhaps something else in your HTTP server is not correctly encoding/decoding the cookie headers to/from the browser?

**Comment by natevw** [comment]
Closing this since afaict there's no problem with JSON strings as inputs that I can find.
