### ISSUE TITLE
"TypeError: crypto.timingSafeEqual is not a function" is occur in Node.js v12.19.0

### ISSUE THREAD

**Issue by hiroshikm** [tj/node-cookie-signature#43]
When I attempt the Example, TypeError came up on my screen at unsign function.

`timingSafeEqual`  is already implemented in [docs](https://nodejs.org/docs/latest-v12.x/api/crypto.html#crypto_crypto_timingsafeequal_a_b)

Does somebody know how resolve this error?

my envs => cookie-signature: v1.2.0, Node: v12.19.0, react: 16.14.0, Next.js: v10

```
var cookie = require('cookie-signature');

var val = cookie.sign('hello', 'tobiiscool');
val.should.equal('hello.DGDUkGlIkCzPz+C0B064FNgHdEjox7ch8tOBGslZ5QI');

var val = cookie.sign('hello', 'tobiiscool');
cookie.unsign(val, 'tobiiscool').should.equal('hello'); <- TypeError at unsign
cookie.unsign(val, 'luna').should.be.false;
```

**Comment by natevw** [comment]
Are you using this server-side or in browser?

**Comment by natevw** [comment]
Closing this, feel free to re-open if you have new information but I'm assuming at this point you may have found some resolution on your own.
